name: android

on:
  workflow_dispatch:
  push:
    paths:
    - Dockerfile.android

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Export
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        outputs: type=local,dest=./,tar=false
        # 强制使用旧版构建模式
        no-cache: true
        platforms: linux/amd64  # 明确指定平台

    - name: Check File Exists
      run: ls -lh ./aria2c

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2-android
        path: ./aria2c
