name: android

on:
  push:
    paths:
      - Dockerfile.android
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        context: .
        tags: aria2-android:latest
        load: true

    - name: Extract Binary
      run: |
        docker ps -aq | xargs -r docker rm -f &>/dev/null || true
        container_id=$(docker create aria2-android:latest)
        docker cp $container_id:/app/aria2c ./aria2c
        docker rm -f $container_id
        if [ ! -f ./aria2c ]; then
          echo "错误：文件提取失败！"
          exit 1
        fi
        ls -lh ./aria2c

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2c-android
        path: ./aria2c
        retention-days: 3
