name: android

on:
  workflow_dispatch:
  push:
    paths:
    - Dockerfile.android

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Export
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        outputs: type=local,dest=./output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2-android
        path: ./output/aria2c
