name: android

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.android

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # 1. 拉取代码
    - uses: actions/checkout@v4

    # 2. 纯编译（无缓存/无优化）
    - name: Build with Docker
      run: |
        docker build \
          -f Dockerfile.android \
          --output type=local,dest=./ \
          .

    # 3. 直接上传产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2c-android
        path: /output/aria2c
