name: android

on:
  workflow_dispatch:
  push:
    paths:
    - Dockerfile.android
  schedule:
  - cron: '30 1 * * *'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        context: .
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aria2
        path: /root/build/aria2/src
